la_poiz_graph:
    resource: "@LaPoizGraphBundle/Resources/config/routing.yml"
    prefix:   /graph/

la_poiz_tab:
    resource: "@LaPoizTableBundle/Resources/config/routing.yml"
    prefix:   /table/

la_poiz_wind:
    resource: "@LaPoizWindBundle/Resources/config/routing.yml"
    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: LaPoizWindBundle:FO:index }

genemu_base64:
    resource: "@GenemuFormBundle/Resources/config/routing/base64.xml"


fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"