<?php

namespace LaPoiz\WindBundle\Repository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderByNumDisplay()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM LaPoizWindBundle:Region r ORDER BY r.numDisplay ASC'
            )
            ->getResult();
    }
}
