<?php

namespace LaPoiz\WindBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpotRepository extends EntityRepository
{
	
	public function findFirst()
	{
		$queryBuilder = $this->createQueryBuilder('spot');
		$queryBuilder->where($queryBuilder->expr()
			->like('spot.nom',"'%Aubin%'"))
			->setMaxResults(1);;
		try {
			return $queryBuilder->getQuery()->getSingleResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}


    public function findAllValid()
    {
        $queryBuilder = $this->createQueryBuilder('spot');
        $queryBuilder->where('spot.isValide = TRUE');
        try {
            return $queryBuilder->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }


    public function findAllNotValid()
    {
        $queryBuilder = $this->createQueryBuilder('spot');
        $queryBuilder->where('spot.isValide = FALSE');
        try {
            return $queryBuilder->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }


    public function findAllWithoutRegion() {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT spot FROM LaPoizWindBundle:Spot spot
            WHERE spot.region IS NULL '
            );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }


}