<?php

namespace LaPoiz\WindBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WebSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebSiteRepository extends EntityRepository
{
	public function findWithName($webSiteName)
	{
		$queryBuilder = $this->createQueryBuilder('webSite');
		$queryBuilder->where($queryBuilder->expr()
			->like('webSite.nom',"'%".$webSiteName."%'"))
			->setMaxResults(1);
		try {
			return $queryBuilder->getQuery()->getSingleResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
}