la_poiz_graph_homepage:
    path:     /hello/{name}
    defaults: { _controller: LaPoizGraphBundle:Default:index }

graph_test1:
    path:     /test1
    defaults: { _controller: LaPoizGraphBundle:WindGraph:test1 }

garph_spot:
    path:     /spot/{id}
    defaults: { _controller: LaPoizGraphBundle:WindGraph:spot }