login:
    path: /login
    defaults: { _controller: LaPoizWindBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout
    defaults: { _controller: LaPoizWindBundle:Default:index }


language_choice:
  path: /language_choice/{langue}
  defaults: { _controller: LaPoizWindBundle:Default:choiceLanguage }



_index:
  defaults: { _controller: LaPoizWindBundle:FO:index }
  path: /index

_fo_spotes_prev_map:
  defaults: { _controller: LaPoizWindBundle:FO:spotsPrevMap }
  path: /map/prev

_fo_spotes_orient_map:
  defaults: { _controller: LaPoizWindBundle:FO:spotsOrientMap}
  path: /map/orientation

_fo_ajax_sites_info_prev:
  defaults: { _controller: LaPoizWindBundle:FOJson:getInfoPrev }
  path: /fo/ajax/sites/prev

_fo_ajax_spots_info_orient:
  defaults: { _controller: LaPoizWindBundle:FOJson:getInfoOrient }
  path: /fo/ajax/spots/orient


_fo_concept:
  defaults: { _controller: LaPoizWindBundle:FO:concept }
  path: /concept

_fo_spot_graph:
  defaults: { _controller: LaPoizWindBundle:FO:spotGraph }
  path: /spot/{id}

_fo_spot_ask_create:
  defaults: { _controller: LaPoizWindBundle:FO:spotAskCreate }
  path: /fo/spot/ask/create

_fo_ajax_spot_ask_create_structure:
  defaults: { _controller: LaPoizWindBundle:FOAjaxAskCreateSpot:structure }
  path: /fo/ajax/spot/ask/create/structure

_fo_ajax_spot_ask_create_nav:
  defaults: { _controller: LaPoizWindBundle:FOAjaxAskCreateSpot:nav }
  path: /fo/ajax/spot/ask/create/nav

_fo_ajax_spot_ask_create_step1:
  defaults: { _controller: LaPoizWindBundle:FOAjaxAskCreateSpot:step1 }
  path: /fo/ajax/spot/ask/create/step1

_fo_ajax_spot_ask_create_step2:
  defaults: { _controller: LaPoizWindBundle:FOAjaxAskCreateSpot:step2 }
  path: /fo/ajax/spot/ask/create/step2/{idContact}

_fo_ajax_spot_ask_create_step3:
  defaults: { _controller: LaPoizWindBundle:FOAjaxAskCreateSpot:step3 }
  path: /fo/ajax/spot/ask/create/step3/{idContact}/{id}

_fo_ajax_spot_ask_create_step4:
  defaults: { _controller: LaPoizWindBundle:FOAjaxAskCreateSpot:step4 }
  path: /fo/ajax/spot/ask/create/step4/{idContact}/{id}

_fo_ajax_spot_ask_create_step5:
  defaults: { _controller: LaPoizWindBundle:FOAjaxAskCreateSpot:step5 }
  path: /fo/ajax/spot/ask/create/step5/{idContact}/{id}

_fo_ajax_spot_ask_create_send:
  defaults: { _controller: LaPoizWindBundle:FOAjaxAskCreateSpot:send }
  path: /fo/ajax/spot/ask/create/send/{idContact}/{id}

_fo_ajax_spot_list_website:
  defaults: { _controller: LaPoizWindBundle:FOJson:listWebsite }
  path: /json/listeWebsite/spot/{id}

_fo_ajax_region_liste_spots_infoNav:
  defaults: { _controller: LaPoizWindBundle:FOAjaxRegion:listSpotsInfoNav }
  path: /fo/ajax/region/spots/infoNav/{id}

_fo_json_spot_data:
  defaults: { _controller: LaPoizWindBundle:FOJson:get }
  path: /fo/json/spot/data/{id}

_fo_json_lapoizGraph_spot_data:
  defaults: { _controller: LaPoizWindBundle:FOJson:getLaPoizGraph }
  path: /fo/json/lapoizgraph/spot/{id}

_fo_json_lapoizGraph_maree_data:
  defaults: { _controller: LaPoizWindBundle:FOJsonMaree:getPlageNavigation }
  path: /fo/json/lapoizgraph/plage/maree/spot/{id}

_fo_json_maree_data:
  defaults: { _controller: LaPoizWindBundle:FOJsonMaree:getMaree }
  path: /fo/json/maree/spot/{id}




_bo_index:
  defaults: { _controller: LaPoizWindBundle:BO:index }
  path: /admin/BO

_bo_spot:
  defaults: { _controller: LaPoizWindBundle:BO:editSpot }
  path: /admin/spot/display/{id}

_bo_spot_create:
  defaults: { _controller: LaPoizWindBundle:BO:createSpot }
  path: /admin/spot/create

_bo_region:
  defaults: { _controller: LaPoizWindBundle:BO:editRegion }
  path: /admin/region/edit/{id}

_bo_region_create:
  defaults: { _controller: LaPoizWindBundle:BO:createRegion }
  path: /admin/region/create

_bo_region_delete:
  defaults: { _controller: LaPoizWindBundle:BO:deleteRegion }
  path: /admin/region/delete/{id}


_bo_dataWindPrev:
  defaults: { _controller: LaPoizWindBundle:BO:dataWindPrev }
  path: /admin/spot/dataWindPrev/{id}


_bo_website_delete:
  defaults: { _controller: LaPoizWindBundle:BOWebSite:delete }
  path: /admin/BO/website/delete/{id}

_bo_website_edit:
  defaults: { _controller: LaPoizWindBundle:BOWebSite:edit }
  path: /admin/BO/website/edit/{id}

_bo_website_create:
  defaults: { _controller: LaPoizWindBundle:BOWebSite:create }
  path: /admin/BO/website/new


_bo_ajax_contact_delete:
  defaults: { _controller: LaPoizWindBundle:BOAjaxContact:delete }
  path: /admin/BO/ajax/contact/delete/{id}


_bo_ajax_spot_delete:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSpot:spotDelete }
  path: /admin/BO/ajax/spot/delete/{id}

_bo_ajax_spot_valid:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSpot:spotValid }
  path: /admin/BO/ajax/spot/valid/{id}

_bo_ajax_dataWindPrev_test_step1:
  defaults: { _controller: LaPoizWindBundle:BOAjaxDataWindPrev:testStep1 }
  path: /admin/BO/ajax/spot/dataWindPrev/test/step1/{id}

_bo_ajax_dataWindPrev_test_step2:
  defaults: { _controller: LaPoizWindBundle:BOAjaxDataWindPrev:testStep2 }
  path: /admin/BO/ajax/spot/dataWindPrev/test/step2/{id}

_bo_ajax_dataWindPrev_test_step3:
  defaults: { _controller: LaPoizWindBundle:BOAjaxDataWindPrev:testStep3 }
  path: /admin/BO/ajax/spot/dataWindPrev/test/step3/{id}

_bo_ajax_dataWindPrev_test_save:
  defaults: { _controller: LaPoizWindBundle:BOAjaxDataWindPrev:testSave }
  path: /admin/BO/ajax/spot/dataWindPrev/test/save/{id}


_bo_ajax_maree_spot_calcule_nbHoure_nav:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSpot:calculNbHoureNav }
  path: /admin/BO/ajax/spot/nbHoureNav/{id}

_bo_ajax_maree_spot_tabData_nbHoure_nav:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSpot:tabDataHoureNav }
  path: /admin/BO/ajax/spot/dataHoureNav/{id}

_bo_ajax_maree_spot_save_nbHoure_nav:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSpot:saveNbHoureNav }
  path: /admin/BO/ajax/spot/save/nbHoureNav/{id}



_bo_ajax_region_add_spot:
  defaults: { _controller: LaPoizWindBundle:BOAjaxRegion:addSpot }
  path: /admin/BO/ajax/region/add/spot/{id}/{idSpot}

_bo_ajax_region_remove_spot:
  defaults: { _controller: LaPoizWindBundle:BOAjaxRegion:removeSpot }
  path: /admin/BO/ajax/region/remove/spot/{id}/{idSpot}

_bo_tools_rosace_convert_png:
  defaults: { _controller: LaPoizWindBundle:BOTools:rosaceConvertPNG }
  path: /admin/BO/tools/rosace/convert/png

_bo_tools_rosace_convert_all_spots:
  defaults: { _controller: LaPoizWindBundle:BOTools:rosaceConvertPNGAllSpots }
  path: /admin/BO/tools/rosace/convert/png/all/spots

_bo_tools_create_allprevision_spot:
  defaults: { _controller: LaPoizWindBundle:BOTools:createAllPrevisionSpot }
  path: /admin/BO/tools/creat/allprevision/spots/{id}


_commande_import:
  defaults: { _controller: LaPoizWindBundle:Commande:import }
  path: /admin/commande/import






_bo_test:
  defaults: { _controller: LaPoizWindBundle:BOTest:index }
  path: /admin/BO/test

_bo_test_maree:
  defaults: { _controller: LaPoizWindBundle:BOTest:maree }
  path: /admin/BO/test/maree

_bo_test_maree_save:
  defaults: { _controller: LaPoizWindBundle:BOTest:mareeSave }
  path: /admin/BO/test/maree/save/{id}


_bo_ajax_maree_getPrev:
  defaults: { _controller: LaPoizWindBundle:BOAjaxMaree:getMareePrev }
  path: /admin/BO/ajax/spot/maree/get/{id}

_bo_ajax_maree_save:
  defaults: { _controller: LaPoizWindBundle:BOAjaxMaree:mareeSave }
  path: /admin/BO/ajax/spot/maree/save/{id}

_bo_ajax_maree_delete:
  defaults: { _controller: LaPoizWindBundle:BOAjaxMaree:mareeDelete }
  path: /admin/BO/ajax/spot/maree/delete/{id}

_bo_ajax_maree_launch_note:
  defaults: { _controller: LaPoizWindBundle:BOAjaxMaree:mareeLaunchNote }
  path: /admin/BO/ajax/spot/maree/note/{id}

_bo_ajax_maree_save_note:
  defaults: { _controller: LaPoizWindBundle:BOAjaxMaree:mareeSaveNote }
  path: /admin/BO/ajax/spot/maree/note/save/{id}

_bo_ajax_maree_create:
  defaults: { _controller: LaPoizWindBundle:BOAjaxMaree:mareeCreate }
  path: /admin/BO/ajax/spot/{id}/maree/create

_bo_ajax_mareeInfo_getDateCoef:
  defaults: { _controller: LaPoizWindBundle:BOAjaxMaree:getDateCoef }
  path: /admin/BO/ajax/maree/dateCoef/{idURLInfoMaree}

_bo_ajax_mareeInfo_getMareeForDay:
  defaults: { _controller: LaPoizWindBundle:BOAjaxMaree:getMareeForDay }
  path: /admin/BO/ajax/maree/{idURLInfoMaree}/forDay/{idDateURLInfoMaree}

_bo_ajax_spot_maree_edit:
  defaults: { _controller: LaPoizWindBundle:BOAjaxMaree:spotMareeEdit }
  path: /admin/BO/ajax/spot/{id}/maree/edit

_bo_ajax_spot_maree_delete:
  defaults: { _controller: LaPoizWindBundle:BOAjaxMaree:spotMareeDelete }
  path: /admin/BO/ajax/spot/{id}/maree/delete

_bo_ajax_spot_edit:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSpot:spotEdit }
  path: /admin/BO/ajax/spot/edit/{id}

_bo_ajax_spot_tempWater_edit:
  defaults: { _controller: LaPoizWindBundle:BOAjaxTempWater:spotTempWaterEdit }
  path: /admin/BO/ajax/spot/{id}/tempwater/edit

_bo_ajax_spot_tempWater_delete:
  defaults: { _controller: LaPoizWindBundle:BOAjaxTempWater:spotTempWaterDelete }
  path: /admin/BO/ajax/spot/{id}/tempwater/delete

_bo_ajax_tempWater_getPrev:
  defaults: { _controller: LaPoizWindBundle:BOAjaxTempWater:getTempWaterPrev }
  path: /admin/BO/ajax/spot/tempwater/get/{id}

_bo_ajax_tempWater_create:
  defaults: { _controller: LaPoizWindBundle:BOAjaxTempWater:tempWaterCreate }
  path: /admin/BO/ajax/spot/{id}/tempWater/create

_bo_ajax_spot_tempWater_save:
  defaults: { _controller: LaPoizWindBundle:BOAjaxTempWater:tempWaterSave }
  path: /admin/BO/ajax/spot/tempWater/save/{id}


_bo_ajax_spot_load_menu_infoSite:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSpotLoadMenu:loadInfoSite }
  path: /admin/BO/ajax/spot/{id}/load/infoSite

_bo_ajax_spot_load_menu_webSite:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSpotLoadMenu:loadWebSite }
  path: /admin/BO/ajax/spot/{id}/load/webSite


_bo_ajax_spot_add_spot_info:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSpot:addSpotInfo }
  path: /admin/BO/ajax/spot/{id}/add/spotInfo

_bo_ajax_spot_edit_spot_info:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSpot:editSpotInfo }
  path: /admin/BO/ajax/spot/edit/spotInfo/{id}

_bo_ajax_spot_remove_spot_info:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSpot:removeSpotInfo }
  path: /admin/BO/ajax/spot/remove/spotInfo/{id}

_bo_ajax_spot_add_site:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSite:spotAddSite }
  path: /admin/BO/ajax/spot/{id}/addSite

_bo_ajax_spot_webSite_delete:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSite:spotSiteDelete }
  path: /admin/BO/ajax/spot/site/delete/{id}

_bo_ajax_spot_edit_site:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSite:spotSiteEdit }
  path: /admin/BO/ajax/spot/site/edit/{id}

_bo_ajax_spot_dataWindPrev:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSite:spotWebSite }
  path: /admin/BO/ajax/spot/webSite/{id}

_bo_ajax_spot_meteo_launch_note:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSite:spotLaunchMeteoNote }
  path: /admin/BO/ajax/spot/meteo/note/{id}

_bo_ajax_spot_meteo_save_note:
  defaults: { _controller: LaPoizWindBundle:BOAjaxSite:spotSaveMeteoNote }
  path: /admin/BO/ajax/spot/meteo/note/save/{id}

_json_spot_detail:
  defaults: { _controller: LaPoizWindBundle:JSon:detailSpot }
  path: /json/spot/{id}












_json_spot_data:
  defaults: { _controller: LaPoizWindBundle:JsonSpot:get, renderTo: null }
  path: /json/spot/data/{id}/{renderTo}

_json_spot_data_test:
  defaults: { _controller: LaPoizWindBundle:JsonSpot:getTest }
  path: /json/spot/data_test/{id}

_json_spot_datatest:
  defaults: { _controller: LaPoizWindBundle:JsonSpot:getTest }
  path: /json/spot/dataTest/{id}


_spot_display:
  defaults: { _controller: LaPoizWindBundle:Spot:display }
  path: /spot/display/{id}

_ajax_spot_history_data_for_dateprev:
  defaults: { _controller: LaPoizWindBundle:AjaxDataWindPrev:spotHistoryDataForDatePrev }
  path: /spot/ajax/dataWindPrev/history/data/date_prev/{id}/{date}


_admin:
  path: /admin
  defaults: { _controller: LaPoizWindBundle:AdminSpot:list }

_admin_spots:
  defaults: { _controller: LaPoizWindBundle:AdminSpot:list }
  path: /admin/spots

_ajax_get_listSpots:
  defaults: { _controller: LaPoizWindBundle:AdminSpot:ajaxGetListSpots }
  path: /ajax/spot/get/list

_ajax_get_add_spot_form:
  defaults: { _controller: LaPoizWindBundle:AdminSpot:ajaxGetAddForm }
  path: /admin/ajax/spot/get/addForm

_ajax_spot_create:
  defaults: { _controller: LaPoizWindBundle:AdminSpot:ajaxCreate }
  path: /admin/ajax/spot/add

_ajax_spot_get_listWebsites:
  defaults: { _controller: LaPoizWindBundle:AdminSpot:ajaxGetListWebsites }
  path: /ajax/spot/get/list/{id}

_ajax_spot_add_website:
  defaults: { _controller: LaPoizWindBundle:AdminSpot:ajaxAddWebsite }
  path: /admin/ajax/spot/add/website

_ajax_spot_get_add_website_form:
  defaults: { _controller: LaPoizWindBundle:AdminSpot:ajaxGetAddWebsiteForm }
  path: /admin/ajax/spot/get/addWebsiteForm/{id}

_admin_spot_display:
  defaults: { _controller: LaPoizWindBundle:AdminSpot:display }
  path: /admin/spot/display/{id}





# a effacer
_admin_spot_edit_a_effacer:
  defaults: { _controller: LaPoizWindBundle:AdminSpot:edit }
  path: /admin/spot/edit/{id}

_ajax_spot_description:
  defaults: { _controller: LaPoizWindBundle:AdminSpot:ajaxDescription }
  path: /ajax/spot/desc/{id}

_ajax_spot_edit:
  defaults: { _controller: LaPoizWindBundle:AdminSpot:ajaxEdit }
  path: /admin/ajax/spot/edit/{id}

_ajax_spot_update:
  defaults: { _controller: LaPoizWindBundle:AdminSpot:ajaxUpdate, id: -1 }
  path: /admin/ajax/spot/update/{id}

# a effacer
_admin_spot_update:
  defaults: { _controller: LaPoizWindBundle:AdminSpot:update }
  path: /admin/spot/update/{id}

_admin_websites:
  defaults: { _controller: LaPoizWindBundle:WebSite:list }
  path: /admin/websites


_admin_dataWindPrev_display:
  defaults: { _controller: LaPoizWindBundle:AdminDataWindPrev:display }
  path: /admin/dataWindPrev/display/{id}

_ajax_dataWindPrev_edit:
  defaults: { _controller: LaPoizWindBundle:AjaxDataWindPrev:ajaxEdit }
  path: /admin/ajax/dataWindPrev/edit/{id}

_admin_dataWindPrev_delete:
  defaults: { _controller: LaPoizWindBundle:AdminDataWindPrev:delete }
  path: /admin/dataWindPrev/delete/{id}

_ajax_dataWindPrev_history_analyse:
  defaults: { _controller: LaPoizWindBundle:AjaxDataWindPrev:historyAnalyse }
  path: /admin/ajax/dataWindPrev/history/analyse/{id}

_ajax_dataWindPrev_history_data:
  defaults: { _controller: LaPoizWindBundle:AjaxDataWindPrev:historyData }
  path: /admin/ajax/dataWindPrev/history/data/{id}

_ajax_dataWindPrev_test:
  defaults: { _controller: LaPoizWindBundle:AjaxDataWindPrevGetData:test }
  path: /admin/ajax/dataWindPrev/test/{id}

_ajax_dataWindPrev_test_remove_previsionDate:
  defaults: { _controller: LaPoizWindBundle:AjaxDataWindPrevGetData:removePrevisionDate }
  path: /admin/ajax/dataWindPrev/test/remove/previsionDate/{id}

_ajax_dataWindPrev_history_data_from_date_analyse:
  defaults: { _controller: LaPoizWindBundle:AjaxDataWindPrev:historyDataFromDateAnalyse }
  path: /admin/ajax/dataWindPrev/history/data/date_analyse/{id}/{date}

_ajax_dataWindPrev_history_data_for_dateprev:
  defaults: { _controller: LaPoizWindBundle:AjaxDataWindPrev:historyDataForDatePrev }
  path: /admin/ajax/dataWindPrev/history/data/date_prev/{id}/{date}


_ajax_spot_data_from_date_filtre:
  defaults: { _controller: LaPoizWindBundle:AjaxSpot:dataForFilterDate }
  path: /spot/ajax/dataWindPrev/data/date/{id}/{date}


_tests:
  defaults: { _controller: LaPoizWindBundle:Test:index }
  path: /admin/tests

_test_notification:
  defaults: { _controller: LaPoizWindBundle:Test:notifications }
  path: /admin/test/notification

_test_multiselect:
  defaults: { _controller: LaPoizWindBundle:Test:multiselect }
  path: /admin/test/multiselect

_test_info:
  defaults: { _controller: LaPoizWindBundle:Test:phpInfo }
  path: /admin/test/phpInfo

_test_ajax_create_dataWindPrev:
  defaults: { _controller: LaPoizWindBundle:Test:createDataWindPrev }
  path: /admin/test/add/dataWindPrev/{id}

_test_ajax_create_spot:
  defaults: { _controller: LaPoizWindBundle:Test:createSpot }
  path: /admin/test/add/spot

_test_goutte:
  defaults: { _controller: LaPoizWindBundle:Test:goutte }
  path: /admin/test/goutte



_bootstrap_demo_index:
  defaults: { _controller: LaPoizWindBundle:Bootstrap:index }
  path: /bootstrap/demo/index