LaPoiz\WindBundle\Entity\Spot:
  properties:
    nom: 
      - NotBlank: ~
    description:
      - NotBlank: ~
    localisationDescription:
      - NotBlank: ~
    gpsLong:
      - NotBlank: ~
    gpsLat:
      - NotBlank: ~